---

- hosts: all
  become: yes
  gather_facts: yes
  become_user: root
  become_method: sudo
  roles:
    - common

- hosts: nokia-ott-pipeline
  become: yes
  gather_facts: yes
  become_user: root
  become_method: sudo
  roles:
    - jenkins

